name: university_search_app
description: A Flutter application for searching universities by country with modern architecture.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # Routing
  go_router: ^12.1.3

  # HTTP Client
  dio: ^5.3.2

  # UI Components
  country_flags: ^3.0.0

  # URL Launcher
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
